config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  resources :groups, only: [:index, :new, :create, :show, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :users,only: [:show,:index,:edit,:update] do
     resources :relationships, only: [:create, :destroy]
     get 'follow' => 'relationships#follow'
     get 'follower' => 'relationships#follower'
  end
  resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  attachment :image

  def joined?(user)
    group_users.where(user_id: user.id).exists?
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence:true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "User"
 belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :messages, dependent: :destroy

  def following?(user)
    following_user.include?(user)
  end

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment=BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end


  def index
    @groups = Group.all
    @book = Book.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.save
    redirect_to groups_path
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end
  
  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @title = params[:title]
    @content = params[:content]
    EventMailer.send_mail(group_users, @title, @content).deliver

  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

def ensure_correct_user
	if @current_user.id != params[:id].to_i
		redirect_to user_path(current_user.id)
	end
end


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th colspan='1'></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= attachment_image_tag(group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.introduction %></td>
        <td><%= group.users.count %></td>
        <% if group.owner_id == current_user.id %>
        <td><%= link_to 'Edit', edit_group_path(group), class: "btn btn-success" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <div class="form-group">
        <label>グループ名</label>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <label>紹介文</label>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
     <div class="form-group">
        <label>グループ画像</label><br/>
        <%=  f.attachment_field :image %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      	<%= render 'layouts/errors', obj: @book %>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <%= render 'index', groups: @groups%>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <div class="form-group">
        <label>グループ名</label>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <label>紹介文</label>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
     <div class="form-group">
        <label>グループ画像</label><br/>
        <%=  f.attachment_field :image %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Event Mail</h3>
      <%= form_with url: group_send_mail_path(@group), method: :get, local:true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <div class="form-group text-right">
        <%= f.submit "送信", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
  <div class="margin_top">内容は以下の通りです。</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"> <%= @title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      	<%= render 'layouts/errors', obj: @book %>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table'>
    <thead>
    <tr>
      <th colspan='1'></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= attachment_image_tag(@group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= @group.name %></td>
        <td><%= @group.introduction %></td>
        <td>
          <% @group.users.where.not(id: @group.id).each do |user| %>
          <%= user.name %>
          <% end %>
        </td>
        <% if @group.owner_id == current_user.id %>
        <td><%= link_to 'Edit', edit_group_path(@group), class: "btn btn-success" %></td>
        <td><%= link_to 'Notice an event', group_new_mail_path(@group), class: 'btn btn-info' %></td>
        <% else %>
          <% if @group.joined?(current_user) %>
          <td><%= link_to 'Leave this group', group_group_users_path(@group), class: 'btn btn-danger', method: :delete %></td>
          <% else %>
          <td><%= link_to 'Join this group', group_group_users_path(@group), class: 'btn btn-success', method: :post %></td>
          <% end %>
        <% end %>
      </tr>
  </tbody>
</table>
    </div>
  </div>
</div>